---
- name: Clone test data.
  git:
    repo: "https://github.com/roocs/mini-esgf-data.git"
    version: "master"
    dest: "{{ roocs_demo_data_dir }}/mini-esgf-data"
    update: yes
    force: yes
  run_once: true
  when: roocs_site == demo

- name: Copy roocs production config
  template:
    src: "./templates/roocs.{{ roocs_site }}.ini.j2"
    dest: "/etc/roocs.ini"
  tags:
    - roocs
    - conf
