---
- name: restart twitcher
  supervisorctl:
    name: "twitcher"
    state: restarted
    # config: "{{ supervisor_config_path}}/supervisord.conf"
    username: "{{ supervisor_user }}"
    password: "{{ supervisor_password }}"

- name: restart nginx
  service:
    name: nginx
    state: restarted
