---
roles:
  - name: andrewrothstein.miniconda
  - name: geerlingguy.supervisor
  - name: geerlingguy.nginx
  - name: geerlingguy.postgresql
  - name: galaxyproject.slurm
  - name: jdauphant.ssl-certs

collections:
  - name: community.general
