---
roles:
  - name: andrewrothstein.miniconda
  - name: andrewrothstein.bash
  - name: andrewrothstein.unarchive-deps
  - name: geerlingguy.repo-epel
  - name: geerlingguy.supervisor
  - name: geerlingguy.nginx
  - name: ANXS.postgresql
  - name: jdauphant.ssl-certs
  - name: arillso.logrotate

collections:
  - name: community.general
