---
roles:
  - name: andrewrothstein.miniconda
  - name: geerlingguy.pip
  - name: geerlingguy.supervisor
  - name: geerlingguy.nginx
  - name: anxs.postgresql
  - name: jdauphant.ssl-certs
  - name: arillso.logrotate

collections:
  - name: community.general
