---
roles:
  - name: andrewrothstein.miniconda
  - name: geerlingguy.pip
  - name: geerlingguy.supervisor
  - name: geerlingguy.nginx
  - src: https://github.com/ANXS/postgresql
    version: v1.16.0
    name: ANXS.postgresql
  - name: jdauphant.ssl-certs
  - name: arillso.logrotate

collections:
  - name: community.general
