---
roles:
  - name: andrewrothstein.miniconda
  - name: geerlingguy.supervisor
  - name: geerlingguy.nginx
  - name: geerlingguy.postgresql
  - name: galaxyproject.slurm

collections:
  - name: community.general
  - name: ansible.posix
