---

# miniconda
# ---------
- src: andrewrothstein.miniconda
- src: andrewrothstein.bash
- src: andrewrothstein.unarchive-deps

# epel
# ----
# Installs the EPEL repository (Extra Packages for Enterprise Linux) for RHEL/CentOS.
- src: geerlingguy.repo-epel

# supervisor
# ----------
- src: geerlingguy.supervisor

# nginx
# -----
- src: geerlingguy.nginx

# postgresql
# ----------
- src: ANXS.postgresql

# ssl-certs
# ---------
- src: jdauphant.ssl-certs
