---
- name: Include source tasks
  include_tasks: source.yml

- name: Include Conda tasks
  include_tasks: conda.yml

- name: Include folder tasks
  include_tasks: folders.yml

- name: Include configuration tasks
  include_tasks: config.yml
