---
- name: Include source tasks
  ansible.builtin.include_tasks:
    file: source.yml
    apply:
      tags:
        - update
  tags:
    - update

- name: Include Conda tasks
  include_tasks: conda.yml

- name: Include WPS application installation tasks
  ansible.builtin.include_tasks:
    file: install.yml
    apply:
      tags:
        - update
  tags:
    - update

- name: Include folder tasks
  ansible.builtin.include_tasks:
    file: folders.yml
    apply:
      tags:
        - update
  tags:
    - update

- name: Include configuration tasks
  ansible.builtin.include_tasks:
    file: config.yml
    apply:
      tags:
        - update
        - live_update
  tags:
    - update
    - live_update
