---
- name: Create folders used by PyWPS and set owner
  file: path={{ item }} state=directory owner={{ wps_user }} group={{ wps_group }} mode=0755
  with_items:
    - /etc/gunicorn
    - /etc/pywps
    - "{{ wps_run_dir }}"
    - /var/log/pywps
    - "{{ wps_basedir }}/db"
  tags:
    - pywps
    - conf

- name: Create output folders used by PyWPS and set owner
  file: path="{{ wps_basedir }}/outputs/{{ item.name }}" state=directory owner={{ wps_user }} group={{ wps_group }} mode=0755
  with_items:
    - "{{ wps_services }}"
  tags:
    - pywps
    - conf

- name: Create temp folders used by PyWPS and set owner
  file: path="{{ wps_basedir }}/tmp/{{ item.name }}" state=directory owner={{ wps_user }} group={{ wps_group }} mode=0755
  with_items:
    - "{{ wps_services }}"
  tags:
    - pywps
    - conf

- name: Update log file permissions
  file: path="/var/log/pywps/{{ item.name }}.log" state=touch owner={{ wps_user }} group={{ wps_group }} mode=0644
  with_items:
    - "{{ wps_services }}"
  tags:
    - pywps
    - conf
