---
- name: Enable SELinux
  ansible.posix.selinux:
    policy: targeted
    state: enforcing

- name: Allow nginx to modify files in /var/run/pywps
  community.general.sefcontext:
    target: '/var/run/pywps(/.*)?'
    setype: httpd_sys_rw_content_t
    state: present

- name: Apply new SELinux file context to filesystem
  command: restorecon -iRv /var/run