---
- include_tasks: clean.yml
- include_tasks: cronjob.yml
- include_tasks: webservice_config.yml
- include_tasks: logrotate.yml
- include_tasks: selinux.yml
  when: selinux_enabled

- include_tasks: slurm.yml
  when: slurm_enabled
  tags:
    - slurm

- include_tasks: sqlite.yml
  when: db_install_sqlite

- include_tasks: fileserver.yml
  when: fs_enabled

- name: Assure PyWPS running at end of playbook
  command: /bin/true
  notify:
    - restart supervisord
  tags:
    - pywps
    - conf

- name: Assure nginx running at end of playbook
  command: /bin/true
  notify:
    - restart nginx
  tags:
    - nginx
    - conf
