---
- include: webservice_config.yml

- include: slurm.yml
  when: slurm_enabled
  tags:
    - slurm

- include: sqlite.yml
  when: db_install_sqlite

- include: fileserver.yml
  when: fs_enabled

- name: Assure PyWPS running at end of playbook
  command: /bin/true
  notify:
    - restart pywps
  tags:
    - pywps
    - conf

- name: Assure nginx running at end of playbook
  command: /bin/true
  notify:
    - restart nginx
  tags:
    - nginx
    - conf
