- name: Install common packages on Debian
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - python3-pip
      - build-essential
      - libssl-dev

- name: Remove unwanted packages on Debian
  apt:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
      - supervisor
