---
- name: Include Debian tasks
  include_tasks: Debian.yml
  when: ansible_os_family == "Debian"

- name: Include Red Hat tasks
  include_tasks: RedHat.yml
  when: ansible_os_family == "RedHat"

- name: Install common packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - wget
    - curl
    - git
    - vim
    - tmux
    - logrotate
  tags:
    - common

- name: Add service group
  group:
    name: "{{ service_group }}"
    gid: "{{ service_gid | default(omit) }}"
    state: present

- name: Add service user
  user:
    name: "{{ service_user }}"
    uid: "{{ service_uid | default(omit) }}"
    group: "{{ service_group }}"
    groups: "{{ service_groups }}"
    system: true
    shell: /sbin/nologin
    createhome: false
    home: "{{ service_user_home }}"
  when: service_add_user
