---
- name: Install common packages on RedHat
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - gcc-c++
      - make
      - libselinux
      # AlmaLinux 9 may provide this through either curl or curl-minimal.
      - /usr/bin/curl
      - cronie

- name: Install packages on RedHat 9 or newer
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - python3-pip
      - langpacks-en
      - glibc-all-langpacks

- name: Remove unwanted packages on RedHat
  yum:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
      - supervisor
