- name: Install common packages on RedHat
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - gcc-c++
      - make

- name: Remove unwanted packages on RedHat
  yum:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
      - supervisor
