---
- name: restart pywps
  supervisorctl:
    name: "{{ item.name }}"
    state: restarted
    username: "{{ supervisor_user }}"
    password: "{{ supervisor_password }}"
  with_items: "{{ wps_services }}"

- name: restart nginx
  service:
    name: nginx
    state: restarted
