---
- name: Clone test data.
  git:
    repo: "https://github.com/roocs/mini-esgf-data.git"
    version: "master"
    dest: "{{ demo_data_dir }}/mini-esgf-data"
    update: yes
    force: yes
  run_once: true
